# Generated by Django 6.0.7 on 2026-08-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
