# Generated by Django 6.0.7 on 2026-08-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_institution_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institution_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
