# Generated by Django 6.0.7 on 2026-09-29 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_institution_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='institution_id',
        ),
    ]
