# Generated by Django 6.0.7 on 2026-08-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='prn',
        ),
    ]
