# Generated by Django 6.0.7 on 2026-08-15 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_studentprofile_prn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='student',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='student',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='github_url',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='linkedin_url',
            new_name='linkedin',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='college',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='division',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='portfolio',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='prn_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='visibility',
            field=models.CharField(choices=[('INSTITUTIONAL', 'Institutional'), ('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='INSTITUTIONAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Internship',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
