# Generated by Django 6.0.7 on 2026-09-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_project_student_remove_skill_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='graduation_status',
            field=models.CharField(choices=[('ONGOING', 'Ongoing'), ('GRADUATED', 'Graduated')], default='ONGOING', max_length=20),
        ),
    ]
